export const columnsData = [
  "Action",
  "Site",
  "Building",
  "Wing",
  "Floor",
  "Area",
  "Room",
  "Asset Name",
  "Asset Code",
  "Serial Number",
  "Asset Type",
  "Client Name",
  "Model Number",
  "Group",
  "Sub Group",
  "Critical",
  "Capacity",
  "Purchase Date",
  "Purchase Cost",
  "Status",
  "Created On",
  "Updated On",
  "Warranty",
  "Warranty Expiry",
  "Commissioning Date",
  "AMC",
  "PPM",
  "Meter Configured",
  "Meter Type",
  "Submeter",
  "Supplier",
];

